"""Render the Markdown content store into a browsable static HTML site."""

from __future__ import annotations

import html
import logging
from pathlib import Path

from .markdown import StoredArticle, load_articles

log = logging.getLogger(__name__)

_CSS = """\
:root{--bg:#0f1217;--panel:#161b22;--ink:#e6e9ef;--muted:#9aa4b2;--line:#262d38;
--accent:#2dd4a7;--accent-ink:#0f1217}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);
font:16px/1.7 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}
a{color:var(--accent);text-decoration:none}
a:hover{text-decoration:underline}
.wrap{max-width:760px;margin:0 auto;padding:0 20px}
header.site{border-bottom:1px solid var(--line);padding:28px 0;margin-bottom:8px}
header.site .brand{font-weight:700;font-size:20px;letter-spacing:.2px}
header.site .tag{color:var(--muted);font-size:13px;margin-top:4px}
.card{display:block;background:var(--panel);border:1px solid var(--line);
border-radius:14px;padding:20px 22px;margin:18px 0;transition:border-color .15s}
.card:hover{border-color:var(--accent)}
.card h2{margin:0 0 6px;font-size:20px}
.card .summary{color:var(--muted);margin:6px 0 12px}
.meta{font-size:12.5px;color:var(--muted);display:flex;gap:10px;flex-wrap:wrap;align-items:center}
.kw{display:inline-block;background:#1d2530;border:1px solid var(--line);
color:var(--muted);border-radius:999px;padding:2px 10px;font-size:12px;margin:2px 4px 2px 0}
.score{background:var(--accent);color:var(--accent-ink);border-radius:999px;
padding:2px 9px;font-weight:600;font-size:12px}
article.post{padding:8px 0 60px}
article.post h1{font-size:30px;line-height:1.25;margin:18px 0 6px}
article.post h2{margin-top:34px;border-bottom:1px solid var(--line);padding-bottom:6px}
article.post img{max-width:100%}
article.post blockquote{border-left:3px solid var(--accent);margin:0;padding:2px 16px;color:var(--muted)}
article.post code{background:#1d2530;padding:.1em .35em;border-radius:5px}
.backlink{display:inline-block;margin:22px 0 6px;font-size:14px}
footer.site{border-top:1px solid var(--line);color:var(--muted);font-size:13px;
padding:24px 0 50px;margin-top:30px}
.empty{color:var(--muted);padding:40px 0}
"""


def _page(title: str, body: str, platform_name: str, depth: int = 0) -> str:
    css_href = ("../" * depth) + "assets/style.css"
    home_href = ("../" * depth) + "index.html"
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)}</title>
<link rel="stylesheet" href="{css_href}">
</head>
<body>
<header class="site"><div class="wrap">
<a class="brand" href="{home_href}">{html.escape(platform_name)}</a>
<div class="tag">Trend-driven market literacy, updated automatically.</div>
</div></header>
<main class="wrap">
{body}
</main>
<footer class="site"><div class="wrap">
Generated by StockScribe. Educational content only — not investment advice.
</div></footer>
</body>
</html>
"""


def _keyword_chips(meta: dict) -> str:
    kws = meta.get("keywords", []) or []
    return "".join(f'<span class="kw">{html.escape(str(k))}</span>' for k in kws[:8])


def _card(article: StoredArticle) -> str:
    meta = article.meta
    href = f"posts/{article.path.stem}.html"
    score = meta.get("virality_score")
    score_html = f'<span class="score">virality {score}</span>' if score is not None else ""
    return f"""<a class="card" href="{href}">
<h2>{html.escape(article.title)}</h2>
<div class="summary">{html.escape(str(meta.get("summary", "")))}</div>
<div class="meta">{html.escape(article.date)} {score_html}</div>
<div>{_keyword_chips(meta)}</div>
</a>"""


def _render_markdown(body: str) -> str:
    import markdown as md  # imported lazily

    return md.markdown(body, extensions=["extra", "sane_lists", "toc"])


def build_site(content_dir: str | Path, site_dir: str | Path, platform_name: str = "The Trading Desk") -> Path:
    """Render every Markdown article into `site_dir`. Returns the index path."""
    site_dir = Path(site_dir)
    posts_dir = site_dir / "posts"
    assets_dir = site_dir / "assets"
    posts_dir.mkdir(parents=True, exist_ok=True)
    assets_dir.mkdir(parents=True, exist_ok=True)
    (assets_dir / "style.css").write_text(_CSS)

    articles = load_articles(content_dir)

    if articles:
        cards = "\n".join(_card(a) for a in articles)
    else:
        cards = '<p class="empty">No articles yet. Run <code>stockscribe run</code> to generate some.</p>'
    (site_dir / "index.html").write_text(
        _page(platform_name, cards, platform_name, depth=0)
    )

    for article in articles:
        body_html = _render_markdown(article.body)
        back = '<a class="backlink" href="../index.html">&larr; All articles</a>'
        post_body = f'<article class="post">{back}\n{body_html}\n{back}</article>'
        (posts_dir / f"{article.path.stem}.html").write_text(
            _page(article.title, post_body, platform_name, depth=1)
        )

    log.info("Built site with %d articles at %s", len(articles), site_dir)
    return site_dir / "index.html"
